### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by orschiro** [stevegrunwell/overcast-mark-as-played#1]
Hi @stevegrunwell, 

Can you help me with the below?

Thanks!

![image](https://user-images.githubusercontent.com/170947/94184471-3e356600-fea4-11ea-96f4-c93c9f43c268.png)

**Comment by stevegrunwell** [comment]
Sure, I'd be happy to help!

If you don't mind, could you please add your browser, version, and operating system here?

**Comment by orschiro** [comment]
Thanks Steve!

Mac 10.15.6 (19G2021) and Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by stevegrunwell** [comment]
Hey @orschiro, thank you for your patience!

As it turns out, Chromium browsers don't support SVG icons in web extensions, so I've just tagged (and am about to submit) [version 1.0.1](https://github.com/stevegrunwell/overcast-mark-as-played/releases/tag/v1.0.1). It may take a few days to appear in the Chrome Web Store, but this should take care of the issue.

Thank you for bringing this to my attention, and please feel free to reach out if the issue persists!

**Comment by orschiro** [comment]
This is great, thanks Steve!

**Comment by stevegrunwell** [comment]
It looks like it was already approved by Google, and [I just installed 1.0.1 fresh from the store](https://chrome.google.com/webstore/detail/overcast-mark-as-played/gaeeolkmbpimllholhblmckdccmlbhnd), so you should be good to go!

**Comment by orschiro** [comment]
Got it, thanks. :)
